import Head from "next/head";
import {useSession, signIn, signOut} from "next-auth/react";
import {useEffect} from "react";
import {checkRefreshTokenError} from "@/util/checkRefreshTokenError";

export default function Home() {
  const {data: session, status} = useSession();
  checkRefreshTokenError();

  return (
    <>
      <Head>
        <title>EasyAuth NextAuth example</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <div className="hero">
          {status !== "loading" && (
            <>
              {session ? (
                <>
                  Signed in as {session.user.email} <br />
                  <button onClick={() => signOut()}>Sign out</button>
                </>
              ) : (
                <>
                  Not signed in . <br />
                  <button onClick={() => signIn("easyauth")}>Sign in</button>
                </>
              )}
            </>
          )}
        </div>
      </main>
    </>
  );
}
