import Head from "next/head";
import {useSession, signIn, signOut} from "next-auth/react";
import {checkRefreshTokenError} from "@/util/checkRefreshTokenError";
import Link from "next/link";

export default function Home() {
  const {data: session, status} = useSession();
  checkRefreshTokenError();

  return (
    <>
      <Head>
        <title>EasyAuth NextAuth example</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <div className="hero">
          {status !== "loading" && (
            <>
              {session ? (
                <>
                  Signed in as {session.user.email} <br />
                  <button
                    onClick={() => {
                      signOut({redirect: false}).then(() => {
                        // To signout from EasyAuth Tenant.
                        window.location.assign(
                          `${
                            process.env.NEXT_PUBLIC_EASYAUTH_TENANT_URL
                          }/logout?target=${btoa(window.location.href)}`
                        );
                      });
                    }}
                  >
                    Sign out
                  </button>
                  <Link href={"/profile"}>
                    <button>EasyAuth user profile</button>
                  </Link>
                </>
              ) : (
                <>
                  Not signed in . <br />
                  <button onClick={() => signIn("easyauth")}>Sign in</button>
                </>
              )}
              <Link href={"/protected"}>
                <button>Protected page</button>
              </Link>
            </>
          )}
        </div>
      </main>
    </>
  );
}
